### ISSUE TITLE
Fastfetch freeze on Void Linux

### ISSUE THREAD

**Issue by DarNCelsius** [LinusDierheimer/fastfetch#16] opened 2021-04-23 13:47 UTC
Fastfetch stops halfway on Void:
![voidfreeze](https://user-images.githubusercontent.com/82701459/115879804-58d7b980-a44a-11eb-9735-b2c55171a092.png)
Here's the output with showerrors:
![voiderrors](https://user-images.githubusercontent.com/82701459/115879855-6725d580-a44a-11eb-85c8-903bbbcd66e1.png)
Good news is the new code in r146 detects it properly. The output on top is from neofetch. Ctrl-C exits fine, it simply stays like this forever.

**Comment by LinusDierheimer** [comment] 2021-04-23 16:47
This seems like a typically deadlock. Most probably in theme code because it hangs just before this output and it is calculated multi threaded. Sadly i can't reproduce it so i need your help for this. In [src/modules/theme.c](https://github.com/LinusDierheimer/fastfetch/blob/master/src/modules/theme.c) you will find the following code: 
```
const FFPlasmaResult* plasma = ffCalculatePlasma(instance);
const FFstrbuf* gtk2 = &ffCalculateGTK2(instance)->theme;
const FFstrbuf* gtk3 = &ffCalculateGTK3(instance)->theme;
const FFstrbuf* gtk4 = &ffCalculateGTK4(instance)->theme;
```
Each of the calculation methods waits for a calculation thread to finish and then return its result. Can you use something like 
 ```puts("after plasma");``` to detect which of these methods hang forever? Probably somewhere a ```pthread_mutex_unlock(&mutex);``` is missing which i cant find.  If you have time you can try to hunt it further down.
   
Just for interest you can try with ```--multithreading false``` and look if this changes anything. (It probably wont tho). 

Thanks

**Comment by LinusDierheimer** [comment] 2021-04-23 18:48
Small update: I actually found some missing `````pthread_mutex_unlock``` in some error handlers in the DConf part of the GTK detection ([commit](https://github.com/LinusDierheimer/fastfetch/commit/283e4f56e949b4b33c0c581ef0de6bef886e926a)). Did this fix your issue?

**Comment by LinusDierheimer** [comment] 2021-04-23 19:26
Also interesting is that resolution doesn't work for you (neither the wayland nor the xrandr nor the x11 implementation). Are the corresponding libraries not called "libwayland-client.so", "libXrandr.so" and "libX11.so"  on void linux?

**Comment by DarNCelsius** [comment] 2021-04-24 06:55
The mutex unlocks did the trick:
![void_r149](https://user-images.githubusercontent.com/82701459/115949962-b4e91f00-a4d8-11eb-8c79-108b65d51d74.png)
Errors:
![void_r149_errors](https://user-images.githubusercontent.com/82701459/115949992-d77b3800-a4d8-11eb-830a-1acb9d9181fd.png)
Here the output from locate:
```
/usr/lib/libX11.so.6
/usr/lib/libX11.so.6.4.0

/usr/lib/libpci.so.3
/usr/lib/libpci.so.3.7.0

/usr/lib/libwayland-client.so.0
/usr/lib/libwayland-client.so.0.3.0

/usr/lib/libXrandr.so.2
/usr/lib/libXrandr.so.2.2.0
```
It also fails to detect the WM, WM Theme and Terminal Font on both void and manjaro, btw.

**Comment by DarNCelsius** [comment] 2021-04-24 07:23
The symlinks are different in Void vs Manjaro. When I made one, it fixed the resolution output:
![void_r149_symlinks2](https://user-images.githubusercontent.com/82701459/115950934-5fb00c00-a4de-11eb-93d6-e25ffe32b427.png)
![void_r149_errors2](https://user-images.githubusercontent.com/82701459/115950940-6474c000-a4de-11eb-8a8b-506057adcd69.png)
The same would probably work for the rest.

**Comment by LinusDierheimer** [comment] 2021-04-24 07:24
Not detecting WM, WM Theme and Terminal Font ist expected behavior as they need to be implemented for each WM / terminal emulator individually and i simply haven't done that for mutter / xfce4-terminal.  As this is a very new project im focusing on making the core more solid at the moment than adding more support for individual use cases (but this will definitely come).

The problem on void is that there doesn't seem to be a symlink without a version (E.g. `/usr/lib/libX11.so` --> `/usr/lib/libX11.so.6` and `/usr/lib/libX11.so.6` --> `/usr/lib/libX11.so.6.4.0` then) which exists on the most common distributions. This can be solved by hardcoding a specific version of library, although this brings problems like
* what happens if the library gets a major update?
* What if somebody has an older version installed?

This could be solved by dynamically looking for files starting with `libX11.so` in `/usr/lib/` and trying with all results but i thinks this will cost a lot of compute time.

**Comment by LinusDierheimer** [comment] 2021-04-24 07:34
> The symlinks are different in Void vs Manjaro. When I made one, it fixed the resolution output:
> ![void_r149_symlinks2](https://user-images.githubusercontent.com/82701459/115950934-5fb00c00-a4de-11eb-93d6-e25ffe32b427.png)
> ![void_r149_errors2](https://user-images.githubusercontent.com/82701459/115950940-6474c000-a4de-11eb-8a8b-506057adcd69.png)
> The same would probably work for the rest.

Small tip: if you symlink `libwayland-client.so` or `libXrandr.so` you should get refresh rate in resolution output, wayland even supports different refresh rates per monitor if this is important for you.

**Comment by LinusDierheimer** [comment] 2021-04-24 10:02
As a solution for you, without creating files not indexed by your package manager, you can put the following lines in `~/.config/fastfetch/config.conf`:
```
--lib-wayland libwayland-client.so.0
--lib-pci libpci.so.3
--lib-dconf libdconf.so.1
```

**Comment by LinusDierheimer** [comment] 2021-04-24 11:14
closing this as the original issue was resolved.

**Closed by LinusDierheimer** 2021-04-24 11:14 UTC
Labels: bug
